### PR TITLE
add hidden input for searched value into form in catalog

### PR DESCRIPTION
**Pull request by igor-kamil**
# Description

added hidden input for searched value into form in catalog

Fixes [WEBUMENIA-1283](https://jira.sng.sk/browse/WEBUMENIA-1283)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rastislav-chynoransky** [comment]
Is this just a hotfix? Do we want the search bar to be part of the filter?

**Comment by igor-kamil** [comment]
@rastislav-chynoransky it's not "search bar" but hidden input
check: https://github.com/SlovakNationalGallery/webumenia.sk/blob/42ecbcc0bc5e9f71573ce7251419c55484f7b6f2/app/Filter/Forms/Types/ItemSearchRequestType.php#L29

it's rendered as `<input class="form-control" type="hidden" id="search" name="search">`

search value was present in the filters form also before - to make it possible to apply filters but to preserve the searched string

**Comment by rastislav-chynoransky** [comment]
I know, but now when you change search bar input it will not interact with filter.

**Comment by igor-kamil** [comment]
@rastislav-chynoransky when you change search bar input, it will just reset filters - what is right behaviour (I think)

**Pull request merged**
