### PR TITLE
[item] add image ratio

### PR DESCRIPTION
**Pull request by rastislav-chynoransky**
# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [x] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by eronisko — APPROVED** [review]
LGTM.

BTW have you considered this as well? https://github.com/woltapp/blurhash

**Comment by eronisko** [comment]
Actually, it might be also worth adding some code that would populate those values for existing data  into the migration.

**Review by igor-kamil — COMMENTED** [review]
this is great! I am happy to see this. So i can finally close https://github.com/SlovakNationalGallery/webumenia.sk/pull/236 afterwards! :D 

it would be great, to calculate ratio for already existing images ( e.g. -> https://github.com/SlovakNationalGallery/webumenia.sk/pull/236/files#diff-69907e1c77b8dfe902ac1fcf9b6fc41bb88a8bfcbe68d091709c410c61f976b7R20-R25 )

also my suggestion is to be aware of division by zero - there might be also corrupted images

the next step is to apply the calculated `image_ratio` everywhere, where we use now evaluating width/height ... but outside of this PR ;)

**Comment by rastislav-chynoransky** [comment]
@eronisko @igor-kamil Thanks! I'd rather use this padding hack for now and we can iterate to blurhash later.
I've created 2 another tasks from your suggestions.
https://jira.sng.sk/browse/WEBUMENIA-1517
https://jira.sng.sk/browse/WEBUMENIA-1518

**Pull request merged**
